/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BrandInfo = IDL.Record({
  'tagline' : IDL.Text,
  'foundingYear' : IDL.Nat,
  'aboutText' : IDL.Text,
});
export const Time = IDL.Int;
export const NewsEvent = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getBrandInfo' : IDL.Func([], [BrandInfo], ['query']),
  'getNewsEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BrandInfo = IDL.Record({
    'tagline' : IDL.Text,
    'foundingYear' : IDL.Nat,
    'aboutText' : IDL.Text,
  });
  const Time = IDL.Int;
  const NewsEvent = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getBrandInfo' : IDL.Func([], [BrandInfo], ['query']),
    'getNewsEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };